#! /bin/bash 

# Check on your optmizations. 


for i in */;do
cd $i;
if ls *01* >/dev/null 2>& 1 ;then             # Check if there are *.out files
cat *01*| grep -l 'Stationary point found'; word=$?

if [ $word -eq 0 ]; then
       echo 'opt done' :${i::-1}
       echo ' ' 
cd ..
elif [ $word -eq 1 ] ; then
       echo ' Something went wrong':${i::-1}
       echo ' ' 
cd ..
fi
else
 echo "Not started yet":${i::-1}
 echo  ' ' 
cd ..
fi
done

