#! /bin/bash 

# Find imaginary frequencies


for i in */;do
cd $i;
if ls *01* >/dev/null 2>& 1 ;then             # Check if there are *.out files
cat *01*| grep -l 'imaginary frequencies'; word=$?

if [ $word -eq 0 ]; then
       echo 'Imaginary frequencies found' :${i::-1}
       echo ' ' 
cd ..
elif [ $word -eq 1 ] ; then
       echo 'ok ':${i::-1}
       echo ' ' 
cd ..
fi
else
 echo "Not started yet":${i::-1}
 echo  ' ' 
cd ..
fi
done

